spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${FEEDOONG_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
