spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${FEEDOONG_DB_URL}
    username: ${FEEDOONG_DB_USERNAME}
    password: ${FEEDOONG_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.sql: debug
    org.springframework.security: debug

jwt:
  secret: "PyjK9n34XsY1RxLoKFedtCm8x3oKWM2V2WkJjtck6XQ="