name: "Refactor"
description: "리팩토링 요소 추가"
labels: "Refactor"
body:
  - type: textarea
    attributes:
      label: 🎙 Describe
      description: 왜 리팩토링을 해야 하는지 설명해 주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 📌 Tasks
      description: 리팩토링을 해야 할 부분에 대해 설명해 주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🎸 기타
      description: 기타 사항이 있다면 여기에 적어주세요.
    validations:
      required: false
